// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: pb/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserCliClient is the client API for UserCli service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCliClient interface {
	GetUser(ctx context.Context, in *UserParam, opts ...grpc.CallOption) (*UserResp, error)
}

type userCliClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCliClient(cc grpc.ClientConnInterface) UserCliClient {
	return &userCliClient{cc}
}

func (c *userCliClient) GetUser(ctx context.Context, in *UserParam, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/user.UserCli/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCliServer is the server API for UserCli service.
// All implementations must embed UnimplementedUserCliServer
// for forward compatibility
type UserCliServer interface {
	GetUser(context.Context, *UserParam) (*UserResp, error)
	mustEmbedUnimplementedUserCliServer()
}

// UnimplementedUserCliServer must be embedded to have forward compatible implementations.
type UnimplementedUserCliServer struct {
}

func (UnimplementedUserCliServer) GetUser(context.Context, *UserParam) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserCliServer) mustEmbedUnimplementedUserCliServer() {}

// UnsafeUserCliServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCliServer will
// result in compilation errors.
type UnsafeUserCliServer interface {
	mustEmbedUnimplementedUserCliServer()
}

func RegisterUserCliServer(s grpc.ServiceRegistrar, srv UserCliServer) {
	s.RegisterService(&UserCli_ServiceDesc, srv)
}

func _UserCli_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCliServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserCli/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCliServer).GetUser(ctx, req.(*UserParam))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCli_ServiceDesc is the grpc.ServiceDesc for UserCli service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCli_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserCli",
	HandlerType: (*UserCliServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserCli_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/user.proto",
}
