update i18n_areas set area_name = "بئر الروحاء" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-0";
update i18n_areas set area_name = "الحار السفلى" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-1";
update i18n_areas set area_name = "الشفية" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-2";
update i18n_areas set area_name = "الاكحل" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-3";
update i18n_areas set area_name = "المفرحات" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-4";
update i18n_areas set area_name = "الرديفة" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-0";
update i18n_areas set area_name = "النبك ابوقصر" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-1";
update i18n_areas set area_name = "الادري" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-2";
update i18n_areas set area_name = "طبرجل" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-3";
update i18n_areas set area_name = "سكاكا" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-4";
update i18n_areas set area_name = "القريات" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-5";
update i18n_areas set area_name = "كارا" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-6";
update i18n_areas set area_name = "الجوف" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-7";
update i18n_areas set area_name = "الحديثة" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-8";
update i18n_areas set area_name = "دومة الجندل" where locale = "ar" and parent_code = "SA-AJ" and area_code = "SA-AJ-9";
update i18n_areas set area_name = "الحجرة" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-0";
update i18n_areas set area_name = "وادي بن حسبل" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-1";
update i18n_areas set area_name = "طريب" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-2";
update i18n_areas set area_name = "تندحة" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-3";
update i18n_areas set area_name = "سبحيكا" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-4";
update i18n_areas set area_name = "المدا" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-5";
update i18n_areas set area_name = "مخواه" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-6";
update i18n_areas set area_name = "المندق" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-7";
update i18n_areas set area_name = "قلوة" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-8";
update i18n_areas set area_name = "بلجرشي" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-9";
update i18n_areas set area_name = "الباحة" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-10";
update i18n_areas set area_name = "الأطاولة" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-11";
update i18n_areas set area_name = "العقيق" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-12";
update i18n_areas set area_name = "فرعة غامد الزناد" where locale = "ar" and parent_code = "SA-BH" and area_code = "SA-BH-13";
update i18n_areas set area_name = "املج" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-0";
update i18n_areas set area_name = "الوجه" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-1";
update i18n_areas set area_name = "تيماء" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-2";
update i18n_areas set area_name = "تبوك" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-3";
update i18n_areas set area_name = "حقل" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-4";
update i18n_areas set area_name = "حالة عمار" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-5";
update i18n_areas set area_name = "ضباء" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-6";
update i18n_areas set area_name = "البدع" where locale = "ar" and parent_code = "SA-TB" and area_code = "SA-TB-7";
update i18n_areas set area_name = "حزم الجلاميد" where locale = "ar" and parent_code = "SA-NB" and area_code = "SA-NB-0";
update i18n_areas set area_name = "طريف" where locale = "ar" and parent_code = "SA-NB" and area_code = "SA-NB-1";
update i18n_areas set area_name = "رفحاء " where locale = "ar" and parent_code = "SA-NB" and area_code = "SA-NB-2";
update i18n_areas set area_name = "عرعر" where locale = "ar" and parent_code = "SA-NB" and area_code = "SA-NB-3";
update i18n_areas set area_name = "بدر الجنوب" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-0";
update i18n_areas set area_name = "شرورة" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-1";
update i18n_areas set area_name = "نجران" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-2";
update i18n_areas set area_name = "ثار" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-3";
update i18n_areas set area_name = "يدمة" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-4";
update i18n_areas set area_name = "حبونا" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-5";
update i18n_areas set area_name = "خباش" where locale = "ar" and parent_code = "SA-NJ" and area_code = "SA-NJ-6";
update i18n_areas set area_name = "السديرة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-0";
update i18n_areas set area_name = "الجموم" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-1";
update i18n_areas set area_name = "عطيف" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-2";
update i18n_areas set area_name = "رضوان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-3";
update i18n_areas set area_name = "المحاني" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-4";
update i18n_areas set area_name = "عرضيه" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-5";
update i18n_areas set area_name = "شميسي" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-6";
update i18n_areas set area_name = "محاني " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-7";
update i18n_areas set area_name = "خرمه " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-8";
update i18n_areas set area_name = "نمره" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-9";
update i18n_areas set area_name = "طيبة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-10";
update i18n_areas set area_name = "ذهبان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-11";
update i18n_areas set area_name = "ذهبان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-12";
update i18n_areas set area_name = "وادي فاطمة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-13";
update i18n_areas set area_name = "تربة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-14";
update i18n_areas set area_name = "الطوال" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-15";
update i18n_areas set area_name = "الطائف" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-16";
update i18n_areas set area_name = "الشميسي" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-17";
update i18n_areas set area_name = "الشرائع" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-18";
update i18n_areas set area_name = "شعيبة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-19";
update i18n_areas set area_name = "رنيا" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-20";
update i18n_areas set area_name = "رابغ" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-21";
update i18n_areas set area_name = "القنفذة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-22";
update i18n_areas set area_name = "النورية" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-23";
update i18n_areas set area_name = "المظيلف" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-24";
update i18n_areas set area_name = "مستورة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-25";
update i18n_areas set area_name = "مكة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-26";
update i18n_areas set area_name = "الليث" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-27";
update i18n_areas set area_name = "الخرمة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-28";
update i18n_areas set area_name = "خليص" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-29";
update i18n_areas set area_name = "الجموم" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-30";
update i18n_areas set area_name = "جدة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-31";
update i18n_areas set area_name = "الجعرانة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-32";
update i18n_areas set area_name = "بحرة الموجود" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-33";
update i18n_areas set area_name = "بحرة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-34";
update i18n_areas set area_name = "الشوقية" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-35";
update i18n_areas set area_name = "عسفان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-36";
update i18n_areas set area_name = "عمق" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-37";
update i18n_areas set area_name = "الهدا" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-38";
update i18n_areas set area_name = "دغبج" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-39";
update i18n_areas set area_name = "ميسان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-40";
update i18n_areas set area_name = "نمره" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-41";
update i18n_areas set area_name = "المحاني " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-42";
update i18n_areas set area_name = "كلاخ" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-43";
update i18n_areas set area_name = "أبو راكة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-44";
update i18n_areas set area_name = "تربه " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-45";
update i18n_areas set area_name = "المويه " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-46";
update i18n_areas set area_name = "السر" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-47";
update i18n_areas set area_name = "اضم " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-48";
update i18n_areas set area_name = "الخرمة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-49";
update i18n_areas set area_name = "الشفا" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-50";
update i18n_areas set area_name = "المحاميد" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-51";
update i18n_areas set area_name = "الكامل" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-52";
update i18n_areas set area_name = "عشيره " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-53";
update i18n_areas set area_name = "حداد بني مالك" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-54";
update i18n_areas set area_name = "عشيرة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-55";
update i18n_areas set area_name = "الخوار" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-56";
update i18n_areas set area_name = "ام الدوم" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-57";
update i18n_areas set area_name = "رنيه" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-58";
update i18n_areas set area_name = "قيا " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-59";
update i18n_areas set area_name = "الشرائع" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-60";
update i18n_areas set area_name = "الروضه" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-61";
update i18n_areas set area_name = "أم الدوم" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-62";
update i18n_areas set area_name = "حدة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-63";
update i18n_areas set area_name = "حي حرازات" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-64";
update i18n_areas set area_name = "العرفاء " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-65";
update i18n_areas set area_name = "ظلم " where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-66";
update i18n_areas set area_name = "بحرة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-67";
update i18n_areas set area_name = "ملكان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-68";
update i18n_areas set area_name = "الجعرانة" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-69";
update i18n_areas set area_name = "ولي العهد" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-70";
update i18n_areas set area_name = "السر" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-71";
update i18n_areas set area_name = "شقصان" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-72";
update i18n_areas set area_name = "حي محاميد" where locale = "ar" and parent_code = "SA-MK" and area_code = "SA-MK-73";
update i18n_areas set area_name = "العيدابي" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-0";
update i18n_areas set area_name = "ضبية" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-1";
update i18n_areas set area_name = "صامطه" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-2";
update i18n_areas set area_name = "صبيا" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-3";
update i18n_areas set area_name = "الخصاوية" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-4";
update i18n_areas set area_name = "الكربوس" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-5";
update i18n_areas set area_name = "جيزان" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-6";
update i18n_areas set area_name = "فرسان" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-7";
update i18n_areas set area_name = "الدرب" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-8";
update i18n_areas set area_name = "ضمد" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-9";
update i18n_areas set area_name = "بيشة" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-10";
update i18n_areas set area_name = "احد المسارحة" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-11";
update i18n_areas set area_name = "ابو عريش" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-12";
update i18n_areas set area_name = "الريث" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-13";
update i18n_areas set area_name = "العارضة" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-14";
update i18n_areas set area_name = "هروب" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-15";
update i18n_areas set area_name = "الدائر" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-16";
update i18n_areas set area_name = "الحرث" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-17";
update i18n_areas set area_name = "فيفاء" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-18";
update i18n_areas set area_name = "الطوال" where locale = "ar" and parent_code = "SA-GZ" and area_code = "SA-GZ-19";
update i18n_areas set area_name = "سميرا" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-0";
update i18n_areas set area_name = "الشنانة" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-1";
update i18n_areas set area_name = "صدين" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-2";
update i18n_areas set area_name = "قفار" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-3";
update i18n_areas set area_name = "منيفت القيد" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-4";
update i18n_areas set area_name = "موقق" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-5";
update i18n_areas set area_name = "الغزالة" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-6";
update i18n_areas set area_name = "بقعاء" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-7";
update i18n_areas set area_name = "بقعاء الشرقية" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-8";
update i18n_areas set area_name = "الشنانه" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-9";
update i18n_areas set area_name = "الوسيطاء" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-10";
update i18n_areas set area_name = "الأجفر" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-11";
update i18n_areas set area_name = "حائل" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-12";
update i18n_areas set area_name = "السليمي" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-13";
update i18n_areas set area_name = "الشملي" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-14";
update i18n_areas set area_name = "الحائط" where locale = "ar" and parent_code = "SA-HL" and area_code = "SA-HL-15";
update i18n_areas set area_name = "المانعية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-0";
update i18n_areas set area_name = "الدغيمية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-1";
update i18n_areas set area_name = "الرابية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-2";
update i18n_areas set area_name = "العيون" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-3";
update i18n_areas set area_name = "نصاب" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-4";
update i18n_areas set area_name = "بقيق" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-5";
update i18n_areas set area_name = "العيون" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-6";
update i18n_areas set area_name = "العضيلية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-7";
update i18n_areas set area_name = "تاروت" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-8";
update i18n_areas set area_name = "تناجيب" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-9";
update i18n_areas set area_name = "سيهات" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-10";
update i18n_areas set area_name = "صرار " where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-11";
update i18n_areas set area_name = "سلوى" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-10";
update i18n_areas set area_name = "صفوى" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-13";
update i18n_areas set area_name = "سفانيه" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-14";
update i18n_areas set area_name = "راس تنورة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-15";
update i18n_areas set area_name = "راس الخير" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-16";
update i18n_areas set area_name = "رحيمة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-17";
update i18n_areas set area_name = "قيسومه" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-18";
update i18n_areas set area_name = "القطيف" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-19";
update i18n_areas set area_name = "قرية العليا" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-20";
update i18n_areas set area_name = "جبل القارة " where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-21";
update i18n_areas set area_name = "العثمانية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-22";
update i18n_areas set area_name = "عجم" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-23";
update i18n_areas set area_name = "النعيرية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-24";
update i18n_areas set area_name = "النابية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-25";
update i18n_areas set area_name = "مليجة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-26";
update i18n_areas set area_name = "المبرز" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-27";
update i18n_areas set area_name = "الخبر" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-28";
update i18n_areas set area_name = "الخفجي" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-29";
update i18n_areas set area_name = "الجبيل" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-30";
update i18n_areas set area_name = "الجفر" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-31";
update i18n_areas set area_name = "الهفوف" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-32";
update i18n_areas set area_name = "الحوية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-33";
update i18n_areas set area_name = "حرض" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-34";
update i18n_areas set area_name = "حفر الباطن" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-35";
update i18n_areas set area_name = "الظهران" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-36";
update i18n_areas set area_name = "الدمام" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-37";
update i18n_areas set area_name = "البطحاء" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-38";
update i18n_areas set area_name = "العوامية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-39";
update i18n_areas set area_name = "عنك" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-40";
update i18n_areas set area_name = "الحساء" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-41";
update i18n_areas set area_name = "عين دار" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-42";
update i18n_areas set area_name = "بقيق" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-43";
update i18n_areas set area_name = "الشعبه" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-44";
update i18n_areas set area_name = "المطيرفي" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-45";
update i18n_areas set area_name = "الحوية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-46";
update i18n_areas set area_name = "المنيزلة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-47";
update i18n_areas set area_name = "جواثا" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-48";
update i18n_areas set area_name = "الطرف" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-49";
update i18n_areas set area_name = "العمران" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-50";
update i18n_areas set area_name = "الفضول" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-51";
update i18n_areas set area_name = "عين النخل" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-52";
update i18n_areas set area_name = "الوزية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-53";
update i18n_areas set area_name = "الجشة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-54";
update i18n_areas set area_name = "الجوية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-55";
update i18n_areas set area_name = "المنطقة الصناعية بالاحساء" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-56";
update i18n_areas set area_name = "الشهارين" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-57";
update i18n_areas set area_name = "المركز" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-58";
update i18n_areas set area_name = "بني معن" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-59";
update i18n_areas set area_name = "الجرن" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-60";
update i18n_areas set area_name = "جليجلة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-61";
update i18n_areas set area_name = "الحصيمه" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-62";
update i18n_areas set area_name = "ام خريسان" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-63";
update i18n_areas set area_name = "ويسة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-64";
update i18n_areas set area_name = "السلطانيـة" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-65";
update i18n_areas set area_name = "البطالية" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-66";
update i18n_areas set area_name = "الشقيق" where locale = "ar" and parent_code = "SA-EA" and area_code = "SA-EA-67";
update i18n_areas set area_name = "طريب" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-0";
update i18n_areas set area_name = "البرك" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-1";
update i18n_areas set area_name = "الواديين" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-2";
update i18n_areas set area_name = "تثليث" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-3";
update i18n_areas set area_name = "التنومه" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-4";
update i18n_areas set area_name = "سراة عبيدة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-5";
update i18n_areas set area_name = "سبت العلايا" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-6";
update i18n_areas set area_name = "رجال ألمع" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-7";
update i18n_areas set area_name = "النماص" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-8";
update i18n_areas set area_name = "محايل عسير" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-9";
update i18n_areas set area_name = "المجاردة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-10";
update i18n_areas set area_name = "خميس مشيط" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-11";
update i18n_areas set area_name = "كارا" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-12";
update i18n_areas set area_name = "الحرجة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-13";
update i18n_areas set area_name = "ظهران الجنوب" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-14";
update i18n_areas set area_name = "بيشة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-15";
update i18n_areas set area_name = "بارق" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-16";
update i18n_areas set area_name = "بلسمر" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-17";
update i18n_areas set area_name = "بلحمر" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-18";
update i18n_areas set area_name = "أحد رفيدة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-19";
update i18n_areas set area_name = "ابها" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-20";
update i18n_areas set area_name = "تمنية" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-21";
update i18n_areas set area_name = "الاثنين" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-22";
update i18n_areas set area_name = "آل يزيد" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-23";
update i18n_areas set area_name = "روضان السليل" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-24";
update i18n_areas set area_name = "ال عرفان" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-25";
update i18n_areas set area_name = "الجر" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-26";
update i18n_areas set area_name = "المقطاع" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-27";
update i18n_areas set area_name = "المضة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-28";
update i18n_areas set area_name = "تندحة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-29";
update i18n_areas set area_name = "الذيبة آل الجحل" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-30";
update i18n_areas set area_name = "آل سرحان" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-31";
update i18n_areas set area_name = "عضاضة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-32";
update i18n_areas set area_name = "يعرى" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-33";
update i18n_areas set area_name = "الفرعاء" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-34";
update i18n_areas set area_name = "وادي ابن هشبل" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-35";
update i18n_areas set area_name = "الغيناء" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-36";
update i18n_areas set area_name = "المسقي" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-37";
update i18n_areas set area_name = "خيبر الجنوب" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-38";
update i18n_areas set area_name = "رغوة" where locale = "ar" and parent_code = "SA-AS" and area_code = "SA-AS-39";
update i18n_areas set area_name = "ساجر" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-0";
update i18n_areas set area_name = "ثرمدا" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-1";
update i18n_areas set area_name = "نفي" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-2";
update i18n_areas set area_name = "الزلفي" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-3";
update i18n_areas set area_name = "وادي الدواسر" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-4";
update i18n_areas set area_name = "أم الجماجم" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-5";
update i18n_areas set area_name = "ضرما" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-6";
update i18n_areas set area_name = "ثادق" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-7";
update i18n_areas set area_name = "السليل" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-8";
update i18n_areas set area_name = "الشفاء" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-9";
update i18n_areas set area_name = "شقراء" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-10";
update i18n_areas set area_name = "صلبوخ" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-11";
update i18n_areas set area_name = "الرويضة" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-12";
update i18n_areas set area_name = "روضة سدير" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-13";
update i18n_areas set area_name = "الرياض" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-14";
update i18n_areas set area_name = "رماح" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-15";
update i18n_areas set area_name = "القويعية" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-16";
update i18n_areas set area_name = "القصب" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-17";
update i18n_areas set area_name = "العيينة" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-18";
update i18n_areas set area_name = "المزاحمية" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-19";
update i18n_areas set area_name = "مرات" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-20";
update i18n_areas set area_name = "المجمعة" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-21";
update i18n_areas set area_name = "الخرج" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-22";
update i18n_areas set area_name = "الخماسين" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-23";
update i18n_areas set area_name = "جلاجل" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-24";
update i18n_areas set area_name = "حوطة سدير" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-25";
update i18n_areas set area_name = "حريملاء" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-26";
update i18n_areas set area_name = "حوطة بني تميم" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-27";
update i18n_areas set area_name = "الحريق" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-28";
update i18n_areas set area_name = "ضرما" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-29";
update i18n_areas set area_name = "الدرعية" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-30";
update i18n_areas set area_name = "الدوادمي" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-31";
update i18n_areas set area_name = "الدلم" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-32";
update i18n_areas set area_name = "الأرطاوية" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-33";
update i18n_areas set area_name = "الغاط" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-34";
update i18n_areas set area_name = "الأفلاج" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-35";
update i18n_areas set area_name = "عفيف" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-36";
update i18n_areas set area_name = "الرين" where locale = "ar" and parent_code = "SA-AR" and area_code = "SA-AR-37";
update i18n_areas set area_name = "صقف" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-0";
update i18n_areas set area_name = "قصيباء" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-1";
update i18n_areas set area_name = "عيون الجوا" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-2";
update i18n_areas set area_name = "كبضه" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-3";
update i18n_areas set area_name = "كحله" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-4";
update i18n_areas set area_name = "ضليع رشيد" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-5";
update i18n_areas set area_name = "الدرعية" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-6";
update i18n_areas set area_name = "الرشاوية " where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-7";
update i18n_areas set area_name = "النبهانيه" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-8";
update i18n_areas set area_name = "المدراج" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-9";
update i18n_areas set area_name = "الخشيبي" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-10";
update i18n_areas set area_name = "الفويلق" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-11";
update i18n_areas set area_name = "البتراء" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-12";
update i18n_areas set area_name = "العمارة" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-13";
update i18n_areas set area_name = "عقلة الصقور" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-14";
update i18n_areas set area_name = "رياض الخبراء" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-15";
update i18n_areas set area_name = "القصيم" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-16";
update i18n_areas set area_name = "عنيزة" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-17";
update i18n_areas set area_name = "مذنب" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-18";
update i18n_areas set area_name = "مذنب" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-19";
update i18n_areas set area_name = "بريدة" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-20";
update i18n_areas set area_name = "البكيرية" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-21";
update i18n_areas set area_name = "البدائع" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-22";
update i18n_areas set area_name = "عين ابن فهيد" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-23";
update i18n_areas set area_name = "الأسياح" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-24";
update i18n_areas set area_name = "الرس" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-25";
update i18n_areas set area_name = "الدليمية" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-26";
update i18n_areas set area_name = "دخنة" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-27";
update i18n_areas set area_name = "القرعاء" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-28";
update i18n_areas set area_name = "الشماسية" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-29";
update i18n_areas set area_name = "الغضا" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-30";
update i18n_areas set area_name = "قبه" where locale = "ar" and parent_code = "SA-AQ" and area_code = "SA-AQ-31";
update i18n_areas set area_name = "فرشة الشامي" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-5";
update i18n_areas set area_name = "الجرنافة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-6";
update i18n_areas set area_name = "السدارة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-7";
update i18n_areas set area_name = "ابيار الماشي" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-8";
update i18n_areas set area_name = "المهد" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-9";
update i18n_areas set area_name = "ينبع البحر" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-10";
update i18n_areas set area_name = "ينبع" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-11";
update i18n_areas set area_name = "العلا" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-12";
update i18n_areas set area_name = "مهد الدهب" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-13";
update i18n_areas set area_name = "المدينة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-14";
update i18n_areas set area_name = "خيبر" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-15";
update i18n_areas set area_name = "الحناكية" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-16";
update i18n_areas set area_name = "بدر" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-17";
update i18n_areas set area_name = "المسيجيد" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-18";
update i18n_areas set area_name = "السدر" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-19";
update i18n_areas set area_name = "العشيرة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-20";
update i18n_areas set area_name = "هبت" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-21";
update i18n_areas set area_name = "الصفاء" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-22";
update i18n_areas set area_name = "وادي الفرع" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-23";
update i18n_areas set area_name = "السدة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-24";
update i18n_areas set area_name = "العيص" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-25";
update i18n_areas set area_name = "الحار العليا" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-26";
update i18n_areas set area_name = "اليتمة" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-27";
update i18n_areas set area_name = "الطرقية" where locale = "ar" and parent_code = "SA-MD" and area_code = "SA-MD-28";



update i18n_areas set area_name = "صبحان الصناعية" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-0";
update i18n_areas set area_name = "صباح السالم" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-1";
update i18n_areas set area_name = "القصور" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-2";
update i18n_areas set area_name = "القرين" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-3";
update i18n_areas set area_name = "المسيله" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-4";
update i18n_areas set area_name = "المسايل" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-5";
update i18n_areas set area_name = "فنيطيس" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-6";
update i18n_areas set area_name = "العدان" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-7";
update i18n_areas set area_name = "أبو الحصانية" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-8";
update i18n_areas set area_name = "أبو فطيرة" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-9";
update i18n_areas set area_name = "مبارك الكبير" where locale = "ar" and parent_code = "KW-MU" and area_code = "KW-MU-10";
update i18n_areas set area_name = "الشامية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-0";
update i18n_areas set area_name = "الروضة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-1";
update i18n_areas set area_name = "قرطبة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-2";
update i18n_areas set area_name = "قبلة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-3";
update i18n_areas set area_name = "القادسية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-4";
update i18n_areas set area_name = "شمال غرب الصليبيخات" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-5";
update i18n_areas set area_name = "المرقاب" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-6";
update i18n_areas set area_name = "المنصورية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-7";
update i18n_areas set area_name = "الخالدية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-8";
update i18n_areas set area_name = "كيفان" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-9";
update i18n_areas set area_name = "غرناطة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-10";
update i18n_areas set area_name = "الفيحاء" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-11";
update i18n_areas set area_name = "الدوحة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-12";
update i18n_areas set area_name = "دسمان" where locale = "ar" and parent_code = "AE-SH" and area_code = "AE-SH-33";
update i18n_areas set area_name = "الدسمة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-14";
update i18n_areas set area_name = "الدعية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-15";
update i18n_areas set area_name = "بنيد القار" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-16";
update i18n_areas set area_name = "حدائق السور" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-17";
update i18n_areas set area_name = "العديلية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-18";
update i18n_areas set area_name = "ضاحية عبدالله السالم" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-19";
update i18n_areas set area_name = "اليرموك" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-20";
update i18n_areas set area_name = "أم سدة - Um Seddah" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-21";
update i18n_areas set area_name = "السرة" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-22";
update i18n_areas set area_name = "الصليبيخات" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-23";
update i18n_areas set area_name = "ميناء الشويخ" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-24";
update i18n_areas set area_name = "الشويخ الصناعية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-25";
update i18n_areas set area_name = "شويخ الصحية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-26";
update i18n_areas set area_name = "شويخ التعليمية" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-27";
update i18n_areas set area_name = "ميناء الشويخ" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-28";
update i18n_areas set area_name = "شرق" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-29";
update i18n_areas set area_name = "Nuzha" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-30";
update i18n_areas set area_name = "مدينة الكويت" where locale = "ar" and parent_code = "KW-KU" and area_code = "KW-KU-31";
update i18n_areas set area_name = "جابر الاحمد" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-0";
update i18n_areas set area_name = "الواحة" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-1";
update i18n_areas set area_name = "خبرة أم العيش" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-2";
update i18n_areas set area_name = "تيماء" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-3";
update i18n_areas set area_name = "الصليبية الصناعية" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-4";
update i18n_areas set area_name = "الصليبية" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-5";
update i18n_areas set area_name = "صبرية - Sabriya" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-6";
update i18n_areas set area_name = "سعد العبدالله" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-7";
update i18n_areas set area_name = "القيروان" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-8";
update i18n_areas set area_name = "القصر" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-9";
update i18n_areas set area_name = "النسيم" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-10";
update i18n_areas set area_name = "النهضة" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-11";
update i18n_areas set area_name = "النعيم" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-12";
update i18n_areas set area_name = "الجهراء المنطقة الصناعية قطعه" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-13";
update i18n_areas set area_name = "منطقة أمغرة صناعية" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-14";
update i18n_areas set area_name = "الجهراء" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-15";
update i18n_areas set area_name = "العبدلي" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-16";
update i18n_areas set area_name = "العيون" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-17";
update i18n_areas set area_name = "كبد" where locale = "ar" and parent_code = "KW-JA" and area_code = "KW-JA-18";
update i18n_areas set area_name = "الزهراء" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-0";
update i18n_areas set area_name = "الصديق" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-1";
update i18n_areas set area_name = "الشعب" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-2";
update i18n_areas set area_name = "الرميثية" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-3";
update i18n_areas set area_name = "ضاحية مبارك العبدالله" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-4";
update i18n_areas set area_name = "حولي" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-5";
update i18n_areas set area_name = "حطين" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-6";
update i18n_areas set area_name = "الشهداء" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-7";
update i18n_areas set area_name = "السلام" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-8";
update i18n_areas set area_name = "البدع" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-9";
update i18n_areas set area_name = "سلوى" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-10";
update i18n_areas set area_name = "السالمية" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-11";
update i18n_areas set area_name = "مشرف" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-12";
update i18n_areas set area_name = "الجابرية" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-13";
update i18n_areas set area_name = "بيان" where locale = "ar" and parent_code = "KW-HA" and area_code = "KW-HA-14";
update i18n_areas set area_name = "صباح الناصر" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-0";
update i18n_areas set area_name = "الرحاب" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-1";
update i18n_areas set area_name = "الرقعي" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-2";
update i18n_areas set area_name = "الري" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-3";
update i18n_areas set area_name = "العمرية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-4";
update i18n_areas set area_name = "مطار الكويت الدولي" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-5";
update i18n_areas set area_name = "جليب الشيوخ" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-6";
update i18n_areas set area_name = "إشبيلية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-7";
update i18n_areas set area_name = "الفردوس" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-8";
update i18n_areas set area_name = "الضجيج" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-9";
update i18n_areas set area_name = "العارضية الحرفية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-10";
update i18n_areas set area_name = "الأندلس" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-11";
update i18n_areas set area_name = "الشدادية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-12";
update i18n_areas set area_name = "الرابية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-13";
update i18n_areas set area_name = "عبدالله المبارك الصباح" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-14";
update i18n_areas set area_name = "خيطان" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-15";
update i18n_areas set area_name = "الفروانية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-16";
update i18n_areas set area_name = "العارضية" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-17";
update i18n_areas set area_name = "أبرق خيطان - Abraq Khaitan" where locale = "ar" and parent_code = "KW-FA" and area_code = "KW-FA-18";
update i18n_areas set area_name = "الوفرة" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-0";
update i18n_areas set area_name = "جنوب الصباحية" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-1";
update i18n_areas set area_name = "الشعيبة قطعه" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-2";
update i18n_areas set area_name = "صباح الأحمد" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-3";
update i18n_areas set area_name = "الرقة" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-4";
update i18n_areas set area_name = "النويصيب" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-5";
update i18n_areas set area_name = "ميناء عبد الله" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-6";
update i18n_areas set area_name = "المنقف" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-7";
update i18n_areas set area_name = "الخيران" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-8";
update i18n_areas set area_name = "جابر العلي" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-9";
update i18n_areas set area_name = "هجيل - Hijil" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-10";
update i18n_areas set area_name = "الفنطاس" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-11";
update i18n_areas set area_name = "الفحيحيل" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-12";
update i18n_areas set area_name = "فهد الأحمد" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-13";
update i18n_areas set area_name = "بنيدر" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-14";
update i18n_areas set area_name = "عقيلة - Aqeela" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-15";
update i18n_areas set area_name = "علي صباح السالم" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-16";
update i18n_areas set area_name = "الزور" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-17";
update i18n_areas set area_name = "الخيران" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-18";
update i18n_areas set area_name = "ميناء عبدالله - Abdulla Port" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-19";
update i18n_areas set area_name = "الظهر" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-20";
update i18n_areas set area_name = "الصباحية" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-21";
update i18n_areas set area_name = "الرقة" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-22";
update i18n_areas set area_name = "المهبولة" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-23";
update i18n_areas set area_name = "هدية" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-24";
update i18n_areas set area_name = "الفحيحيل" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-25";
update i18n_areas set area_name = "الأحمدي" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-26";
update i18n_areas set area_name = "أبو حليفة" where locale = "ar" and parent_code = "KW-AH" and area_code = "KW-AH-27";