
update i18n_countries set country_name = "Bahrain" where locale = 'ar' and country_code2 = 'BH';
update i18n_countries set country_name = "Bahrain" where locale = 'en' and country_code2 = 'BH';
update i18n_countries set country_name = "Qatar" where locale = 'ar' and country_code2 = 'QA';
update i18n_countries set country_name = "Qatar" where locale = 'en' and country_code2 = 'QA';
update i18n_countries set country_name = "Oman" where locale = 'ar' and country_code2 = 'OM';
update i18n_countries set country_name = "Oman" where locale = 'en' and country_code2 = 'OM';



update i18n_provinces set province_name="Capital Governorate" where locale = "en" and country_code2 = "BH" and province_code = "BH-CP";
update i18n_provinces set province_name="Capital Governorate" where locale = "ar" and country_code2 = "BH" and province_code = "BH-CP";
update i18n_provinces set province_name="首都省" where locale = "zh-CN" and country_code2 = "BH" and province_code = "BH-CP";
update i18n_provinces set province_name="Southern Governorate" where locale = "en" and country_code2 = "BH" and province_code = "BH-SN";
update i18n_provinces set province_name="Southern Governorate" where locale = "ar" and country_code2 = "BH" and province_code = "BH-SN";
update i18n_provinces set province_name="南方省" where locale = "zh-CN" and country_code2 = "BH" and province_code = "BH-SN";
update i18n_provinces set province_name="Muharraq Governorate" where locale = "en" and country_code2 = "BH" and province_code = "BH-MU";
update i18n_provinces set province_name="Muharraq Governorate" where locale = "ar" and country_code2 = "BH" and province_code = "BH-MU";
update i18n_provinces set province_name="穆哈拉格省" where locale = "zh-CN" and country_code2 = "BH" and province_code = "BH-MU";
update i18n_provinces set province_name="Northern Governorate" where locale = "en" and country_code2 = "BH" and province_code = "BH-NT";
update i18n_provinces set province_name="Northern Governorate" where locale = "ar" and country_code2 = "BH" and province_code = "BH-NT";
update i18n_provinces set province_name="北方省" where locale = "zh-CN" and country_code2 = "BH" and province_code = "BH-NT";
update i18n_provinces set province_name="Central Governorate" where locale = "en" and country_code2 = "BH" and province_code = "BH-CN";
update i18n_provinces set province_name="Central Governorate" where locale = "ar" and country_code2 = "BH" and province_code = "BH-CN";
update i18n_provinces set province_name="中央省" where locale = "zh-CN" and country_code2 = "BH" and province_code = "BH-CN";
update i18n_provinces set province_name="Ad-Dakhiliyah {Ad-Dakhiliyah}" where locale = "en" and country_code2 = "OM" and province_code = "OM-DA";
update i18n_provinces set province_name="Ad-Dakhiliyah {Ad-Dakhiliyah}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-DA";
update i18n_provinces set province_name="内地省（奈兹瓦）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-DA";
update i18n_provinces set province_name="Al-Batinah {Al-Batinah}" where locale = "en" and country_code2 = "OM" and province_code = "OM-BA";
update i18n_provinces set province_name="Al-Batinah {Al-Batinah}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-BA";
update i18n_provinces set province_name="巴提奈省" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-BA";
update i18n_provinces set province_name="Al-Wusta {Al-Wusta}" where locale = "en" and country_code2 = "OM" and province_code = "OM-WU";
update i18n_provinces set province_name="Al-Wusta {Al-Wusta}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-WU";
update i18n_provinces set province_name="中部省（海马）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-WU";
update i18n_provinces set province_name="Ash-Sharqiyah {Ash-Sharqiyah}" where locale = "en" and country_code2 = "OM" and province_code = "OM-SH";
update i18n_provinces set province_name="Ash-Sharqiyah {Ash-Sharqiyah}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-SH";
update i18n_provinces set province_name="东部省" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-SH";
update i18n_provinces set province_name="Az-zahirah(incl. Al-Buraymī) {Az-Zahirah}" where locale = "en" and country_code2 = "OM" and province_code = "OM-ZA";
update i18n_provinces set province_name="Az-zahirah(incl. Al-Buraymī) {Az-Zahirah}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-ZA";
update i18n_provinces set province_name="扎希拉省（伊卜里）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-ZA";
update i18n_provinces set province_name="Masqat[Muscat] {Masqat}" where locale = "en" and country_code2 = "OM" and province_code = "OM-MA";
update i18n_provinces set province_name="Masqat[Muscat] {Masqat}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-MA";
update i18n_provinces set province_name="马斯喀特省（马斯喀特）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-MA";
update i18n_provinces set province_name="Musandam (Ru'us al-Gibā)" where locale = "en" and country_code2 = "OM" and province_code = "OM-MU";
update i18n_provinces set province_name="Musandam (Ru'us al-Gibā)" where locale = "ar" and country_code2 = "OM" and province_code = "OM-MU";
update i18n_provinces set province_name="穆桑代姆省（海塞卜）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-MU";
update i18n_provinces set province_name="zufār [Dhofar] {Zufar}" where locale = "en" and country_code2 = "OM" and province_code = "OM-ZU";
update i18n_provinces set province_name="zufār [Dhofar] {Zufar}" where locale = "ar" and country_code2 = "OM" and province_code = "OM-ZU";
update i18n_provinces set province_name="佐法尔省（塞拉莱）" where locale = "zh-CN" and country_code2 = "OM" and province_code = "OM-ZU";
update i18n_provinces set province_name="Al Daayen" where locale = "en" and country_code2 = "QA" and province_code = "QA-DA";
update i18n_provinces set province_name="Al Daayen" where locale = "ar" and country_code2 = "QA" and province_code = "QA-DA";
update i18n_provinces set province_name="达延" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-DA";
update i18n_provinces set province_name="Al Khor and Al Thakhira" where locale = "en" and country_code2 = "QA" and province_code = "QA-KT";
update i18n_provinces set province_name="Al Khor and Al Thakhira" where locale = "ar" and country_code2 = "QA" and province_code = "QA-KT";
update i18n_provinces set province_name="豪尔" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-KT";
update i18n_provinces set province_name="Al Wakra" where locale = "en" and country_code2 = "QA" and province_code = "QA-WA";
update i18n_provinces set province_name="Al Wakra" where locale = "ar" and country_code2 = "QA" and province_code = "QA-WA";
update i18n_provinces set province_name="沃克拉" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-WA";
update i18n_provinces set province_name="Al Rayyan" where locale = "en" and country_code2 = "QA" and province_code = "QA-RA";
update i18n_provinces set province_name="Al Rayyan" where locale = "ar" and country_code2 = "QA" and province_code = "QA-RA";
update i18n_provinces set province_name="赖扬" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-RA";
update i18n_provinces set province_name="Al Shamal" where locale = "en" and country_code2 = "QA" and province_code = "QA-SM";
update i18n_provinces set province_name="Al Shamal" where locale = "ar" and country_code2 = "QA" and province_code = "QA-SM";
update i18n_provinces set province_name="沙马尔" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-SM";
update i18n_provinces set province_name="Doha" where locale = "en" and country_code2 = "QA" and province_code = "QA-DH";
update i18n_provinces set province_name="Doha" where locale = "ar" and country_code2 = "QA" and province_code = "QA-DH";
update i18n_provinces set province_name="多哈" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-DH";
update i18n_provinces set province_name="Umm Salal" where locale = "en" and country_code2 = "QA" and province_code = "QA-US";
update i18n_provinces set province_name="Umm Salal" where locale = "ar" and country_code2 = "QA" and province_code = "QA-US";
update i18n_provinces set province_name="乌姆锡拉勒" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-US";
update i18n_provinces set province_name="Al Sheehaniya" where locale = "en" and country_code2 = "QA" and province_code = "QA-SH";
update i18n_provinces set province_name="Al Sheehaniya" where locale = "ar" and country_code2 = "QA" and province_code = "QA-SH";
update i18n_provinces set province_name="沙哈尼亚" where locale = "zh-CN" and country_code2 = "QA" and province_code = "QA-SH";




update i18n_areas set area_name = "Zayed Town" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-0";
update i18n_areas set area_name = "Zayed Town" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-0";
update i18n_areas set area_name = "Tubli" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-1";
update i18n_areas set area_name = "Tubli" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-1";
update i18n_areas set area_name = "Sitra" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-2";
update i18n_areas set area_name = "Sitra" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-2";
update i18n_areas set area_name = "Sanad" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-3";
update i18n_areas set area_name = "Sanad" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-3";
update i18n_areas set area_name = "Salmabad" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-4";
update i18n_areas set area_name = "Salmabad" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-4";
update i18n_areas set area_name = "Nasfah" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-5";
update i18n_areas set area_name = "Nasfah" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-5";
update i18n_areas set area_name = "Jordab" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-6";
update i18n_areas set area_name = "Jordab" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-6";
update i18n_areas set area_name = "Isa Town" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-7";
update i18n_areas set area_name = "Isa Town" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-7";
update i18n_areas set area_name = "Aali" where locale = "en" and parent_code = "BH-CN" and area_code = "BH-CN-8";
update i18n_areas set area_name = "Aali" where locale = "ar" and parent_code = "BH-CN" and area_code = "BH-CN-8";
update i18n_areas set area_name = "Um Alhassam" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-0";
update i18n_areas set area_name = "Um Alhassam" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-0";
update i18n_areas set area_name = "Seef" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-1";
update i18n_areas set area_name = "Seef" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-1";
update i18n_areas set area_name = "Adliya" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-10";
update i18n_areas set area_name = "Adliya" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-10";
update i18n_areas set area_name = "Salmaniya" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-2";
update i18n_areas set area_name = "Salmaniya" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-2";
update i18n_areas set area_name = "Ras Ruman" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-3";
update i18n_areas set area_name = "Ras Ruman" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-3";
update i18n_areas set area_name = "Qudaibiya" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-4";
update i18n_areas set area_name = "Qudaibiya" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-4";
update i18n_areas set area_name = "Qofool" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-5";
update i18n_areas set area_name = "Qofool" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-5";
update i18n_areas set area_name = "Mina Salman" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-6";
update i18n_areas set area_name = "Mina Salman" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-6";
update i18n_areas set area_name = "Manama" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-7";
update i18n_areas set area_name = "Manama" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-7";
update i18n_areas set area_name = "Juffair" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-8";
update i18n_areas set area_name = "Juffair" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-8";
update i18n_areas set area_name = "Ghurayfah" where locale = "en" and parent_code = "BH-CP" and area_code = "BH-CP-9";
update i18n_areas set area_name = "Ghurayfah" where locale = "ar" and parent_code = "BH-CP" and area_code = "BH-CP-9";
update i18n_areas set area_name = "Tala Island" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-0";
update i18n_areas set area_name = "Tala Island" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-0";
update i18n_areas set area_name = "Samaheej" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-1";
update i18n_areas set area_name = "Samaheej" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-1";
update i18n_areas set area_name = "Qalali" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-2";
update i18n_areas set area_name = "Qalali" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-2";
update i18n_areas set area_name = "Muharraq" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-3";
update i18n_areas set area_name = "Muharraq" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-3";
update i18n_areas set area_name = "Hidd" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-4";
update i18n_areas set area_name = "Hidd" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-4";
update i18n_areas set area_name = "Dair" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-5";
update i18n_areas set area_name = "Dair" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-5";
update i18n_areas set area_name = "Busaiteen" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-6";
update i18n_areas set area_name = "Busaiteen" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-6";
update i18n_areas set area_name = "Arad" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-7";
update i18n_areas set area_name = "Arad" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-7";
update i18n_areas set area_name = "Amwaj" where locale = "en" and parent_code = "BH-MU" and area_code = "BH-MU-8";
update i18n_areas set area_name = "Amwaj" where locale = "ar" and parent_code = "BH-MU" and area_code = "BH-MU-8";
update i18n_areas set area_name = "Zallaq" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-0";
update i18n_areas set area_name = "Zallaq" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-0";
update i18n_areas set area_name = "Umm Alsabban (Mohammadiya)" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-1";
update i18n_areas set area_name = "Umm Alsabban (Mohammadiya)" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-1";
update i18n_areas set area_name = "Qella" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-10";
update i18n_areas set area_name = "Qella" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-10";
update i18n_areas set area_name = "Qadam" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-11";
update i18n_areas set area_name = "Qadam" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-11";
update i18n_areas set area_name = "North Sehla" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-12";
update i18n_areas set area_name = "North Sehla" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-12";
update i18n_areas set area_name = "Musalla" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-13";
update i18n_areas set area_name = "Musalla" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-13";
update i18n_areas set area_name = "Muqaba" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-14";
update i18n_areas set area_name = "Muqaba" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-14";
update i18n_areas set area_name = "Meqsha" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-15";
update i18n_areas set area_name = "Meqsha" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-15";
update i18n_areas set area_name = "Markh" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-16";
update i18n_areas set area_name = "Markh" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-16";
update i18n_areas set area_name = "Malikiya" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-17";
update i18n_areas set area_name = "Malikiya" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-17";
update i18n_areas set area_name = "Khamis" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-18";
update i18n_areas set area_name = "Khamis" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-18";
update i18n_areas set area_name = "Karzakan" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-19";
update i18n_areas set area_name = "Karzakan" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-19";
update i18n_areas set area_name = "Tashan" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-2";
update i18n_areas set area_name = "Tashan" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-2";
update i18n_areas set area_name = "Karrana" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-20";
update i18n_areas set area_name = "Karrana" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-20";
update i18n_areas set area_name = "Jidhafs" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-21";
update i18n_areas set area_name = "Jidhafs" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-21";
update i18n_areas set area_name = "Jid Alhaj" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-22";
update i18n_areas set area_name = "Jid Alhaj" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-22";
update i18n_areas set area_name = "Jiblat Habshi" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-23";
update i18n_areas set area_name = "Jiblat Habshi" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-23";
update i18n_areas set area_name = "Jasra" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-24";
update i18n_areas set area_name = "Jasra" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-24";
update i18n_areas set area_name = "Jannusan" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-25";
update i18n_areas set area_name = "Jannusan" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-25";
update i18n_areas set area_name = "Janabiya" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-26";
update i18n_areas set area_name = "Janabiya" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-26";
update i18n_areas set area_name = "Hillat Abdulsaleh" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-27";
update i18n_areas set area_name = "Hillat Abdulsaleh" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-27";
update i18n_areas set area_name = "Hamala" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-28";
update i18n_areas set area_name = "Hamala" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-28";
update i18n_areas set area_name = "Hamad Town" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-29";
update i18n_areas set area_name = "Hamad Town" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-29";
update i18n_areas set area_name = "South Sehla" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-3";
update i18n_areas set area_name = "South Sehla" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-3";
update i18n_areas set area_name = "Hajar" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-30";
update i18n_areas set area_name = "Hajar" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-30";
update i18n_areas set area_name = "Dumistan" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-31";
update i18n_areas set area_name = "Dumistan" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-31";
update i18n_areas set area_name = "Diraz" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-32";
update i18n_areas set area_name = "Diraz" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-32";
update i18n_areas set area_name = "Dar Kulaib" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-33";
update i18n_areas set area_name = "Dar Kulaib" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-33";
update i18n_areas set area_name = "Buri" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-34";
update i18n_areas set area_name = "Buri" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-34";
update i18n_areas set area_name = "Buquwa" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-35";
update i18n_areas set area_name = "Buquwa" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-35";
update i18n_areas set area_name = "Budaiya" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-36";
update i18n_areas set area_name = "Budaiya" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-36";
update i18n_areas set area_name = "Barbar" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-37";
update i18n_areas set area_name = "Barbar" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-37";
update i18n_areas set area_name = "Bani Jamra" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-38";
update i18n_areas set area_name = "Bani Jamra" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-38";
update i18n_areas set area_name = "Abu Saiba" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-39";
update i18n_areas set area_name = "Abu Saiba" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-39";
update i18n_areas set area_name = "Shakhura" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-4";
update i18n_areas set area_name = "Shakhura" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-4";
update i18n_areas set area_name = "Abu Beham" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-40";
update i18n_areas set area_name = "Abu Beham" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-40";
update i18n_areas set area_name = "Shahrakan" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-5";
update i18n_areas set area_name = "Shahrakan" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-5";
update i18n_areas set area_name = "Sakheir" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-6";
update i18n_areas set area_name = "Sakheir" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-6";
update i18n_areas set area_name = "Sadad" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-7";
update i18n_areas set area_name = "Sadad" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-7";
update i18n_areas set area_name = "Saar" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-8";
update i18n_areas set area_name = "Saar" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-8";
update i18n_areas set area_name = "Qurayya" where locale = "en" and parent_code = "BH-NT" and area_code = "BH-NT-9";
update i18n_areas set area_name = "Qurayya" where locale = "ar" and parent_code = "BH-NT" and area_code = "BH-NT-9";
update i18n_areas set area_name = "West Riffa" where locale = "en" and parent_code = "BH-SN" and area_code = "BH-SN-0";
update i18n_areas set area_name = "West Riffa" where locale = "ar" and parent_code = "BH-SN" and area_code = "BH-SN-0";
update i18n_areas set area_name = "East Riffa" where locale = "en" and parent_code = "BH-SN" and area_code = "BH-SN-1";
update i18n_areas set area_name = "East Riffa" where locale = "ar" and parent_code = "BH-SN" and area_code = "BH-SN-1";
update i18n_areas set area_name = "Ar-Rustāq {Ar-Rustaq}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-0";
update i18n_areas set area_name = "Ar-Rustāq {Ar-Rustaq}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-0";
update i18n_areas set area_name = "Ṣuḥār [Sohar] {Suhar}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-1";
update i18n_areas set area_name = "Ṣuḥār [Sohar] {Suhar}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-1";
update i18n_areas set area_name = "As-Suwayq" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-10";
update i18n_areas set area_name = "As-Suwayq" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-10";
update i18n_areas set area_name = "Aṣ-Ṣuwamḥān (Barka')" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-11";
update i18n_areas set area_name = "Aṣ-Ṣuwamḥān (Barka')" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-11";
update i18n_areas set area_name = "As-Suwādī as-Sāḥil (Barka')" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-12";
update i18n_areas set area_name = "As-Suwādī as-Sāḥil (Barka')" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-12";
update i18n_areas set area_name = "Ar-Rumays (Barka')" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-13";
update i18n_areas set area_name = "Ar-Rumays (Barka')" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-13";
update i18n_areas set area_name = "Al-Maṣna'ah {Al-Masnaah}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-14";
update i18n_areas set area_name = "Al-Maṣna'ah {Al-Masnaah}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-14";
update i18n_areas set area_name = "Al-Khābūrah {Al-Khaburah}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-15";
update i18n_areas set area_name = "Al-Khābūrah {Al-Khaburah}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-15";
update i18n_areas set area_name = "Al-Ḥuwayl (Ṣaḥam) {Al-Huwayl }" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-16";
update i18n_areas set area_name = "Al-Ḥuwayl (Ṣaḥam) {Al-Huwayl }" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-16";
update i18n_areas set area_name = "Al-Budāyah (As-Suwayq)" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-17";
update i18n_areas set area_name = "Al-Budāyah (As-Suwayq)" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-17";
update i18n_areas set area_name = "Shināṣ {Shinas}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-2";
update i18n_areas set area_name = "Shināṣ {Shinas}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-2";
update i18n_areas set area_name = "Ṣaḥam {Saham}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-3";
update i18n_areas set area_name = "Ṣaḥam {Saham}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-3";
update i18n_areas set area_name = "Nakhal" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-4";
update i18n_areas set area_name = "Nakhal" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-4";
update i18n_areas set area_name = "Liwā {Liwa}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-5";
update i18n_areas set area_name = "Liwā {Liwa}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-5";
update i18n_areas set area_name = "Khaḑrā' ās-Sa'd (As-Suwayq)" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-6";
update i18n_areas set area_name = "Khaḑrā' ās-Sa'd (As-Suwayq)" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-6";
update i18n_areas set area_name = "Ḍiyān al-Bū Sa'īd (As-Suwayq)" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-7";
update i18n_areas set area_name = "Ḍiyān al-Bū Sa'īd (As-Suwayq)" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-7";
update i18n_areas set area_name = "Dīl al-'Abd as-Salām (Ṣaḥam)" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-8";
update i18n_areas set area_name = "Dīl al-'Abd as-Salām (Ṣaḥam)" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-8";
update i18n_areas set area_name = "Barka' {Barka}" where locale = "en" and parent_code = "OM-BA" and area_code = "OM-BA-9";
update i18n_areas set area_name = "Barka' {Barka}" where locale = "ar" and parent_code = "OM-BA" and area_code = "OM-BA-9";
update i18n_areas set area_name = "Samā'il {Samail}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-0";
update i18n_areas set area_name = "Samā'il {Samail}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-0";
update i18n_areas set area_name = "Nizwā {Nizwa}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-1";
update i18n_areas set area_name = "Nizwā {Nizwa}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-1";
update i18n_areas set area_name = "Izkī {Izki}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-2";
update i18n_areas set area_name = "Izkī {Izki}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-2";
update i18n_areas set area_name = "Fanjā (Bidbid) {Fanja }" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-3";
update i18n_areas set area_name = "Fanjā (Bidbid) {Fanja }" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-3";
update i18n_areas set area_name = "Birkat al-Mawz (Nizwā)" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-4";
update i18n_areas set area_name = "Birkat al-Mawz (Nizwā)" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-4";
update i18n_areas set area_name = "Bahlā' {Bahla}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-5";
update i18n_areas set area_name = "Bahlā' {Bahla}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-5";
update i18n_areas set area_name = "Al-Ḥamrā' {Al-Hamra}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-6";
update i18n_areas set area_name = "Al-Ḥamrā' {Al-Hamra}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-6";
update i18n_areas set area_name = "Ādam {Adam}" where locale = "en" and parent_code = "OM-DA" and area_code = "OM-DA-7";
update i18n_areas set area_name = "Ādam {Adam}" where locale = "ar" and parent_code = "OM-DA" and area_code = "OM-DA-7";
update i18n_areas set area_name = "Qurayyāt {Qurayyat}" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-0";
update i18n_areas set area_name = "Qurayyāt {Qurayyat}" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-0";
update i18n_areas set area_name = "Maṭraḥ {Matrah}" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-1";
update i18n_areas set area_name = "Maṭraḥ {Matrah}" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-1";
update i18n_areas set area_name = "Muscat" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-2";
update i18n_areas set area_name = "Muscat" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-2";
update i18n_areas set area_name = "Bawshar" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-3";
update i18n_areas set area_name = "Bawshar" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-3";
update i18n_areas set area_name = "As-Sīb {As-Sib}" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-4";
update i18n_areas set area_name = "As-Sīb {As-Sib}" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-4";
update i18n_areas set area_name = "Al-'Āmarāt {Al-Amarat}" where locale = "en" and parent_code = "OM-MA" and area_code = "OM-MA-5";
update i18n_areas set area_name = "Al-'Āmarāt {Al-Amarat}" where locale = "ar" and parent_code = "OM-MA" and area_code = "OM-MA-5";
update i18n_areas set area_name = "Khaṣab {Khasab}" where locale = "en" and parent_code = "OM-MU" and area_code = "OM-MU-0";
update i18n_areas set area_name = "Khaṣab {Khasab}" where locale = "ar" and parent_code = "OM-MU" and area_code = "OM-MU-0";
update i18n_areas set area_name = "Dibā al-Bay'ah {Diba al-Bayah}" where locale = "en" and parent_code = "OM-MU" and area_code = "OM-MU-1";
update i18n_areas set area_name = "Dibā al-Bay'ah {Diba al-Bayah}" where locale = "ar" and parent_code = "OM-MU" and area_code = "OM-MU-1";
update i18n_areas set area_name = "Ṣūr {Sur}" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-0";
update i18n_areas set area_name = "Ṣūr {Sur}" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-0";
update i18n_areas set area_name = "Sanāw (Al-Muḍaybī) {Sanaw}" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-1";
update i18n_areas set area_name = "Sanāw (Al-Muḍaybī) {Sanaw}" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-1";
update i18n_areas set area_name = "Ja'alan Banī Bū Ḥassan" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-2";
update i18n_areas set area_name = "Ja'alan Banī Bū Ḥassan" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-2";
update i18n_areas set area_name = "Ja'alan Banī Bū 'Alī" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-3";
update i18n_areas set area_name = "Ja'alan Banī Bū 'Alī" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-3";
update i18n_areas set area_name = "Ibra" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-4";
update i18n_areas set area_name = "Ibra" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-4";
update i18n_areas set area_name = "Ḥī as-Shrūq (Ṣūr)" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-5";
update i18n_areas set area_name = "Ḥī as-Shrūq (Ṣūr)" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-5";
update i18n_areas set area_name = "Al-Muḍaybī {Al-Mudaybi}" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-6";
update i18n_areas set area_name = "Al-Muḍaybī {Al-Mudaybi}" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-6";
update i18n_areas set area_name = "Al-Mintirib (Badiyah)" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-7";
update i18n_areas set area_name = "Al-Mintirib (Badiyah)" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-7";
update i18n_areas set area_name = "Al-Kāmil wal-Wāfī" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-8";
update i18n_areas set area_name = "Al-Kāmil wal-Wāfī" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-8";
update i18n_areas set area_name = "Al-Āshkharah" where locale = "en" and parent_code = "OM-SH" and area_code = "OM-SH-9";
update i18n_areas set area_name = "Al-Āshkharah" where locale = "ar" and parent_code = "OM-SH" and area_code = "OM-SH-9";
update i18n_areas set area_name = "Mahout" where locale = "en" and parent_code = "OM-WU" and area_code = "OM-WU-0";
update i18n_areas set area_name = "Mahout" where locale = "ar" and parent_code = "OM-WU" and area_code = "OM-WU-0";
update i18n_areas set area_name = "Haymā {Hayma}" where locale = "en" and parent_code = "OM-WU" and area_code = "OM-WU-1";
update i18n_areas set area_name = "Haymā {Hayma}" where locale = "ar" and parent_code = "OM-WU" and area_code = "OM-WU-1";
update i18n_areas set area_name = "Buraimi" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-0";
update i18n_areas set area_name = "Buraimi" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-0";
update i18n_areas set area_name = "Yanqul" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-1";
update i18n_areas set area_name = "Yanqul" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-1";
update i18n_areas set area_name = "Ḍank {Dank}" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-2";
update i18n_areas set area_name = "Ḍank {Dank}" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-2";
update i18n_areas set area_name = "Al-'Arāqī (Ibrī) {Al-Araqi}" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-3";
update i18n_areas set area_name = "Al-'Arāqī (Ibrī) {Al-Araqi}" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-3";
update i18n_areas set area_name = "Ad-Darīz (Ibrī) {Ad-Dariz}" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-4";
update i18n_areas set area_name = "Ad-Darīz (Ibrī) {Ad-Dariz}" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-4";
update i18n_areas set area_name = "'Ibrī {Ibri}" where locale = "en" and parent_code = "OM-ZA" and area_code = "OM-ZA-5";
update i18n_areas set area_name = "'Ibrī {Ibri}" where locale = "ar" and parent_code = "OM-ZA" and area_code = "OM-ZA-5";
update i18n_areas set area_name = "Ṣalālah {Salalah}" where locale = "en" and parent_code = "OM-ZU" and area_code = "OM-ZU-0";
update i18n_areas set area_name = "Ṣalālah {Salalah}" where locale = "ar" and parent_code = "OM-ZU" and area_code = "OM-ZU-0";
update i18n_areas set area_name = "Zone 70" where locale = "en" and parent_code = "QA-DA" and area_code = "QA-DA-0";
update i18n_areas set area_name = "Zone 70" where locale = "ar" and parent_code = "QA-DA" and area_code = "QA-DA-0";
update i18n_areas set area_name = "Zone 69" where locale = "en" and parent_code = "QA-DA" and area_code = "QA-DA-1";
update i18n_areas set area_name = "Zone 69" where locale = "ar" and parent_code = "QA-DA" and area_code = "QA-DA-1";
update i18n_areas set area_name = "Zone 65" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-0";
update i18n_areas set area_name = "Zone 65" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-0";
update i18n_areas set area_name = "Zone 63" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-1";
update i18n_areas set area_name = "Zone 63" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-1";
update i18n_areas set area_name = "Zone 25" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-10";
update i18n_areas set area_name = "Zone 25" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-10";
update i18n_areas set area_name = "Zone 23" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-11";
update i18n_areas set area_name = "Zone 23" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-11";
update i18n_areas set area_name = "Zone 62" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-12";
update i18n_areas set area_name = "Zone 62" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-12";
update i18n_areas set area_name = "Zone 57" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-13";
update i18n_areas set area_name = "Zone 57" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-13";
update i18n_areas set area_name = "Zone 51" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-14";
update i18n_areas set area_name = "Zone 51" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-14";
update i18n_areas set area_name = "Zone 33" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-15";
update i18n_areas set area_name = "Zone 33" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-15";
update i18n_areas set area_name = "Zone 44" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-16";
update i18n_areas set area_name = "Zone 44" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-16";
update i18n_areas set area_name = "Zone 18" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-17";
update i18n_areas set area_name = "Zone 18" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-17";
update i18n_areas set area_name = "Zone 14" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-18";
update i18n_areas set area_name = "Zone 14" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-18";
update i18n_areas set area_name = "Zone 12" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-19";
update i18n_areas set area_name = "Zone 12" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-19";
update i18n_areas set area_name = "Zone 61" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-2";
update i18n_areas set area_name = "Zone 61" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-2";
update i18n_areas set area_name = "Zone 07" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-20";
update i18n_areas set area_name = "Zone 07" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-20";
update i18n_areas set area_name = "Zone 68" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-21";
update i18n_areas set area_name = "Zone 68" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-21";
update i18n_areas set area_name = "Zone 67" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-22";
update i18n_areas set area_name = "Zone 67" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-22";
update i18n_areas set area_name = "Zone 49" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-23";
update i18n_areas set area_name = "Zone 49" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-23";
update i18n_areas set area_name = "Zone 47" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-24";
update i18n_areas set area_name = "Zone 47" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-24";
update i18n_areas set area_name = "Zone 43" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-25";
update i18n_areas set area_name = "Zone 43" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-25";
update i18n_areas set area_name = "Zone 41" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-26";
update i18n_areas set area_name = "Zone 41" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-26";
update i18n_areas set area_name = "Zone 37" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-27";
update i18n_areas set area_name = "Zone 37" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-27";
update i18n_areas set area_name = "Zone 32" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-28";
update i18n_areas set area_name = "Zone 32" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-28";
update i18n_areas set area_name = "Zone 24" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-29";
update i18n_areas set area_name = "Zone 24" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-29";
update i18n_areas set area_name = "Zone 60" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-3";
update i18n_areas set area_name = "Zone 60" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-3";
update i18n_areas set area_name = "Zone 19" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-30";
update i18n_areas set area_name = "Zone 19" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-30";
update i18n_areas set area_name = "Zone 13" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-31";
update i18n_areas set area_name = "Zone 13" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-31";
update i18n_areas set area_name = "Zone 04" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-32";
update i18n_areas set area_name = "Zone 04" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-32";
update i18n_areas set area_name = "Zone 66" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-33";
update i18n_areas set area_name = "Zone 66" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-33";
update i18n_areas set area_name = "Zone 64" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-34";
update i18n_areas set area_name = "Zone 64" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-34";
update i18n_areas set area_name = "Zone 58" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-35";
update i18n_areas set area_name = "Zone 58" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-35";
update i18n_areas set area_name = "Zone 50" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-36";
update i18n_areas set area_name = "Zone 50" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-36";
update i18n_areas set area_name = "Zone 39" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-37";
update i18n_areas set area_name = "Zone 39" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-37";
update i18n_areas set area_name = "Zone 31" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-38";
update i18n_areas set area_name = "Zone 31" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-38";
update i18n_areas set area_name = "Zone 21" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-39";
update i18n_areas set area_name = "Zone 21" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-39";
update i18n_areas set area_name = "Zone 46" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-4";
update i18n_areas set area_name = "Zone 46" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-4";
update i18n_areas set area_name = "Zone 20" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-40";
update i18n_areas set area_name = "Zone 20" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-40";
update i18n_areas set area_name = "Zone 06" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-41";
update i18n_areas set area_name = "Zone 06" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-41";
update i18n_areas set area_name = "Zone 02" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-42";
update i18n_areas set area_name = "Zone 02" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-42";
update i18n_areas set area_name = "Zone 48" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-43";
update i18n_areas set area_name = "Zone 48" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-43";
update i18n_areas set area_name = "Zone 29" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-44";
update i18n_areas set area_name = "Zone 29" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-44";
update i18n_areas set area_name = "Zone 22" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-45";
update i18n_areas set area_name = "Zone 22" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-45";
update i18n_areas set area_name = "Zone 15" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-46";
update i18n_areas set area_name = "Zone 15" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-46";
update i18n_areas set area_name = "Zone 03" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-47";
update i18n_areas set area_name = "Zone 03" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-47";
update i18n_areas set area_name = "Zone 36" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-48";
update i18n_areas set area_name = "Zone 36" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-48";
update i18n_areas set area_name = "Zone 35" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-49";
update i18n_areas set area_name = "Zone 35" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-49";
update i18n_areas set area_name = "Zone 45" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-5";
update i18n_areas set area_name = "Zone 45" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-5";
update i18n_areas set area_name = "Zone 34" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-50";
update i18n_areas set area_name = "Zone 34" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-50";
update i18n_areas set area_name = "Zone 30" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-51";
update i18n_areas set area_name = "Zone 30" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-51";
update i18n_areas set area_name = "Zone 28" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-52";
update i18n_areas set area_name = "Zone 28" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-52";
update i18n_areas set area_name = "Zone 26" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-53";
update i18n_areas set area_name = "Zone 26" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-53";
update i18n_areas set area_name = "Zone 17" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-54";
update i18n_areas set area_name = "Zone 17" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-54";
update i18n_areas set area_name = "Zone 16" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-55";
update i18n_areas set area_name = "Zone 16" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-55";
update i18n_areas set area_name = "Zone 05" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-56";
update i18n_areas set area_name = "Zone 05" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-56";
update i18n_areas set area_name = "Zone 01" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-57";
update i18n_areas set area_name = "Zone 01" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-57";
update i18n_areas set area_name = "Zone 42" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-6";
update i18n_areas set area_name = "Zone 42" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-6";
update i18n_areas set area_name = "Zone 40" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-7";
update i18n_areas set area_name = "Zone 40" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-7";
update i18n_areas set area_name = "Zone 38" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-8";
update i18n_areas set area_name = "Zone 38" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-8";
update i18n_areas set area_name = "Zone 27" where locale = "en" and parent_code = "QA-DH" and area_code = "QA-DH-9";
update i18n_areas set area_name = "Zone 27" where locale = "ar" and parent_code = "QA-DH" and area_code = "QA-DH-9";
update i18n_areas set area_name = "Zone 76" where locale = "en" and parent_code = "QA-KT" and area_code = "QA-KT-0";
update i18n_areas set area_name = "Zone 76" where locale = "ar" and parent_code = "QA-KT" and area_code = "QA-KT-0";
update i18n_areas set area_name = "Zone 75" where locale = "en" and parent_code = "QA-KT" and area_code = "QA-KT-1";
update i18n_areas set area_name = "Zone 75" where locale = "ar" and parent_code = "QA-KT" and area_code = "QA-KT-1";
update i18n_areas set area_name = "Zone 74" where locale = "en" and parent_code = "QA-KT" and area_code = "QA-KT-2";
update i18n_areas set area_name = "Zone 74" where locale = "ar" and parent_code = "QA-KT" and area_code = "QA-KT-2";
update i18n_areas set area_name = "Zone 96" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-0";
update i18n_areas set area_name = "Zone 96" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-0";
update i18n_areas set area_name = "Zone 55" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-1";
update i18n_areas set area_name = "Zone 55" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-1";
update i18n_areas set area_name = "Zone 51" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-2";
update i18n_areas set area_name = "Zone 51" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-2";
update i18n_areas set area_name = "Zone 83" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-3";
update i18n_areas set area_name = "Zone 83" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-3";
update i18n_areas set area_name = "Zone 53" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-4";
update i18n_areas set area_name = "Zone 53" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-4";
update i18n_areas set area_name = "Zone 56" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-5";
update i18n_areas set area_name = "Zone 56" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-5";
update i18n_areas set area_name = "Zone 97" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-6";
update i18n_areas set area_name = "Zone 97" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-6";
update i18n_areas set area_name = "Zone 54" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-7";
update i18n_areas set area_name = "Zone 54" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-7";
update i18n_areas set area_name = "Zone 52" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-8";
update i18n_areas set area_name = "Zone 52" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-8";
update i18n_areas set area_name = "Zone 81" where locale = "en" and parent_code = "QA-RA" and area_code = "QA-RA-9";
update i18n_areas set area_name = "Zone 81" where locale = "ar" and parent_code = "QA-RA" and area_code = "QA-RA-9";
update i18n_areas set area_name = "Zone 85" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-0";
update i18n_areas set area_name = "Zone 85" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-0";
update i18n_areas set area_name = "Zone 84" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-1";
update i18n_areas set area_name = "Zone 84" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-1";
update i18n_areas set area_name = "Zone 82" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-2";
update i18n_areas set area_name = "Zone 82" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-2";
update i18n_areas set area_name = "Zone 86" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-3";
update i18n_areas set area_name = "Zone 86" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-3";
update i18n_areas set area_name = "Zone 80" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-4";
update i18n_areas set area_name = "Zone 80" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-4";
update i18n_areas set area_name = "Zone 73" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-5";
update i18n_areas set area_name = "Zone 73" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-5";
update i18n_areas set area_name = "Zone 72" where locale = "en" and parent_code = "QA-SH" and area_code = "QA-SH-6";
update i18n_areas set area_name = "Zone 72" where locale = "ar" and parent_code = "QA-SH" and area_code = "QA-SH-6";
update i18n_areas set area_name = "Zone 77" where locale = "en" and parent_code = "QA-SM" and area_code = "QA-SM-0";
update i18n_areas set area_name = "Zone 77" where locale = "ar" and parent_code = "QA-SM" and area_code = "QA-SM-0";
update i18n_areas set area_name = "Zone 78" where locale = "en" and parent_code = "QA-SM" and area_code = "QA-SM-1";
update i18n_areas set area_name = "Zone 78" where locale = "ar" and parent_code = "QA-SM" and area_code = "QA-SM-1";
update i18n_areas set area_name = "Zone 79" where locale = "en" and parent_code = "QA-SM" and area_code = "QA-SM-2";
update i18n_areas set area_name = "Zone 79" where locale = "ar" and parent_code = "QA-SM" and area_code = "QA-SM-2";
update i18n_areas set area_name = "Zone 71" where locale = "en" and parent_code = "QA-US" and area_code = "QA-US-0";
update i18n_areas set area_name = "Zone 71" where locale = "ar" and parent_code = "QA-US" and area_code = "QA-US-0";
update i18n_areas set area_name = "Zone 95" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-0";
update i18n_areas set area_name = "Zone 95" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-0";
update i18n_areas set area_name = "Zone 91" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-1";
update i18n_areas set area_name = "Zone 91" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-1";
update i18n_areas set area_name = "Zone 90" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-2";
update i18n_areas set area_name = "Zone 90" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-2";
update i18n_areas set area_name = "Zone 94" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-3";
update i18n_areas set area_name = "Zone 94" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-3";
update i18n_areas set area_name = "Zone 98" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-4";
update i18n_areas set area_name = "Zone 98" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-4";
update i18n_areas set area_name = "Zone 93" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-5";
update i18n_areas set area_name = "Zone 93" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-5";
update i18n_areas set area_name = "Zone 92" where locale = "en" and parent_code = "QA-WA" and area_code = "QA-WA-6";
update i18n_areas set area_name = "Zone 92" where locale = "ar" and parent_code = "QA-WA" and area_code = "QA-WA-6";
